//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadHistory
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string ChannelTitle { get; set; }
        public string Duration { get; set; }
        public string ThumbnailLink { get; set; }
        public string DownloadDate { get; set; }
        public string VideoId { get; set; }
    }
}
