//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public long Id { get; set; }
        public string MP3Path { get; set; }
        public string VideoPath { get; set; }
        public string AutomaticDownload { get; set; }
        public string PlaySound { get; set; }
        public string SoundFile { get; set; }
        public string CopyFromClipboard { get; set; }
        public string ShowNotification { get; set; }
        public string KeepMp4 { get; set; }
    }
}
