//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Youtube2Mp3DatabaseEntities : DbContext
    {
        public Youtube2Mp3DatabaseEntities()
            : base("name=Youtube2Mp3DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DownloadHistory> DownloadHistory { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
    }
}
